### PR TITLE
PresenterComponent: now calling checkRequirements() on createComponent<n...

### PR DESCRIPTION
**Pull request by fprochazka**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Is this still relevant?

**Comment by enumag** [comment]
How did I forget about this? Of course it's still relevant. https://github.com/nette/application/pull/158

**Comment by TomasVotruba** [comment]
This can be closed then @dg 

@enumag Thank you, we will continue on the https://github.com/nette/application/pull/158

**Comment by dg** [comment]
So I am closing it here.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request closed without merging**
