### PR TITLE
gitter badge

### PR DESCRIPTION
**Pull request by chemix**
added gitter badge to readme file

### CODE REVIEW

**Comment by JanTvrdik** [comment]
I'd suggest to wait a while until we are confident we want to use gitter.

**Comment by fprochazka** [comment]
I agree with @JanTvrdik. But I'm not sure how we're going to find that out without more people joining.

**Comment by JanTvrdik** [comment]
@fprochazka The badge will have little impact on number of people. It's better to tweet about it and write about it on forum.

**Comment by chemix** [comment]
I don't see any number... https://github.com/steida/este
I think, if the link to gitter is on documentation page (http://doc.nette.org/en/2.3/ chat room), why not here? It takes time... and more ways to gitter is better imho

**Comment by dg** [comment]
It looks badly vertically centered https://github.com/chemix/nette/blob/patch-1/readme.md

**Comment by chemix** [comment]
new line?

**Comment by dg** [comment]
https://img.shields.io/badge/GITTER-join%20chat-green.svg is 20px height so it fits better.

**Comment by chemix** [comment]
:+1:

**Pull request closed without merging**
