### PR TITLE
composer.json: removed nette/deprecated, nette/safe-stream and nette/tokenizer

### PR DESCRIPTION
**Pull request by dg**
(Not intended for 2.3)

### CODE REVIEW

**Comment by enumag** [comment]
:+1: But don't forget about [this line](https://github.com/nette/bootstrap/blob/ac973f6f3e5a8ba39953cdc5437d17a9169df007/src/Bridges/Framework/NetteExtension.php#L278).

**Comment by dg** [comment]
I know nette/bootstrap#32

**Comment by hrach** [comment]
Why? What are the reasons?

**Comment by dg** [comment]
Just a thought for the future. It is not intended for 2.3

**Comment by hrach** [comment]
Well, it makes sence for deprecated. But I'm not sure for others, because it's not obvious whats behind the deccision not to include this specific packages. :-)

**Pull request closed without merging**
